name: build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        target: 
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
          - linux-arm64-musl
          - linux-amd64-musl
          - windows-arm64
          - android-arm64
          - windows-win7-amd64
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Go mod tidy
        run: go mod tidy
        
      - name: Setup web
        run: bash build.sh dev web
      - name: Install MinGW for Win7 build
        if: matrix.target == 'windows-win7-amd64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64
      - name: Build Win7 Binary
        if: matrix.target == 'windows-win7-amd64'
        run: |
          bash build.sh release win7
          mkdir -p build

      - name: Build
        if: matrix.target != 'windows-win7-amd64'
        run: |
          export BASE="https://download.wireguard.com/qemu-test/toolchains/20211123/"
          if [[ ${{ matrix.target }} == *"musl"* ]]; then
            if [[ ${{ matrix.target }} == *"arm"* ]]; then
              curl -L -o musl.tgz "${BASE}arm-linux-musleabihf-cross.tgz"
            else
              curl -L -o musl.tgz "${BASE}x86_64-linux-musl-cross.tgz"
            fi
            sudo tar xf musl.tgz --strip-components 1 -C /usr/local
            rm -f musl.tgz
          fi
          bash build.sh release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alist_${{ env.SHA }}_${{ matrix.target }}
          path: build/*
